### ISSUE TITLE
EoT Controller on Synology Docker

### ISSUE THREAD

**Issue by Vonkenboer** [ubiquiti/eot-controller#2]
Is it possible to get the controller running on a Synology with Docker package?

I tried, but it stops with messages in the logs:

![afbeelding](https://user-images.githubusercontent.com/20646433/37868933-57e26f42-2faf-11e8-8de2-ee11f86f4802.png)

Any advise?

**Comment by janisskuja** [comment]
Hi! It seems to me, that controller can't connect to `postgreSQL` on `localhost:6432`. Controller requires PostgreSQL on `localhost:6432` and Redis on `localhost:6379`. Hope this helps. For reference here's an example of `docker-compose.yml`:
```
version: '2'

services:
  postgres:
    container_name: ueot-postgres
    image: postgres:9.6.1-alpine
    restart: always
    volumes:
      - /home/ueot/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 6432:5432
    environment:
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    container_name: ueot-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  ueot:
    container_name: ueot
    image: ubnt/eot:1.2.6
    restart: always
    volumes:
      - /home/ueot/logs:/app/logs
    network_mode: host
    environment:
      - PLATFORM=linux
    depends_on:
      - postgres
      - redis
```
